### ISSUE TITLE
Stop left menu from hiding

### ISSUE THREAD

**Issue by CGB0** [puikinsh/Bootstrap-Admin-Template#75]
When I resize the window width to less than 768 the left menu completely disappears. How can I stop this? When I have the window less than 1250 I remove the left menu text and only display icons. This is how I would like it to remain. I need some kind of menu on the left hand side.

I have tried playing around in the core.js file but did not find anything useful there.

Any help would be appreciated. Thanks,

Colin

**Comment by onokumus** [comment]
@OldProgramCoder 
Change the following less files and recompile.
```less
// new layout.less
/*********************************************************/
/*                 Template Layout                       */
/*********************************************************/


#wrap,
#top,
.head,
.Footer {
  .clearfix();
}

.Wrap, #wrap {
  margin: 0 auto;
  position: relative;
}

#left,
#right {
  .transition(all .3s ease-in-out);
  z-index: 999;
}

#left {
  position: relative;
  float: left;
  width: @miniSidebarWidth;
}

  #content {
    .transition(all .3s ease-in-out);
    overflow: hidden;
  }

@media (min-width: 1250px) {
#left {
      width: @SidebarWidth;
    }
}

#right {
  position: fixed;
  top: 0;
  bottom: 0;
  overflow-y: auto;
  right: -@SidebarWidth;
  width: @SidebarWidth;
}


.sidebar-right-opened {
  position: relative;
  right: @SidebarWidth;
  #right {
    right: 0;
  }
  &.fixed .navbar-fixed-top {
    right: @SidebarWidth;
  }
}

@media (min-width: @screen-sm-min) {

  .sidebar-right-opened {
       right: 0;
       margin-right: @SidebarWidth;
    .navbar-fixed-top {
       margin-right: @SidebarWidth;
    }
  }
}

@media (min-width: @screen-lg-min) {
  body.boxed {
    margin-bottom: 0;
    .Wrap, #wrap, .Footer, #top .navbar.navbar-fixed-top {
      max-width: 1170px;
      margin-left: auto;
      margin-right: auto;
    }
    .Footer, #footer {
      position: relative;
    }
  }
}

/* ================== END Template Layout ============== */
```

```less
// new left.less
/*********************************************************/
/*          Begin LEFT Styles                           */
/*********************************************************/

.user-media {

  .user-link {
    .center-block();
    position: relative;

    .user-img {
      margin: 10px auto;
    }
    .user-label {
      position: absolute;
      top: -6px;
      right: 6px;
    }
  }

  .user-link {
    float: left;
    .user-img {
      margin: 10px;
    }
    .user-label {
      top: 6px;
      right: 0;
    }
  }
  .media-body {
    margin-left: 12px;
    h5.media-heading {
      color: #fff;
      padding-top: 8px;
      margin-bottom: 3px;
    }
    ul.user-info li {
      color: #ccc;
    }
  }
  .clearfix();
}


.user-wrapper{
  position: absolute;
  top: 0;
  left: -100%;
  display: none;
  min-width: @SidebarWidth;
}



.user-media-toggleHover{
  font-size: 18px;
  color: #fff;
  padding: 10px;
  text-align: center;
  cursor: pointer;
  display: inherit;
}

.user-media:hover .user-wrapper{
  left: 100%;
  display: inherit;
  z-index: 9999;
}

@media (min-width: 1250px) {
  .user-media-toggleHover {
    display: none;
  }
  .user-wrapper{
    position: relative;
    top: 0;
    left:0 !important;
    display: inherit;
  }

}

/* ============== END LEFT Styles ================= */
```

```less 
// new menu.less
#menu {
  &, ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
  li,
  a {
    position: relative;
    display: block;
    color: #f4f4f4;
    outline: 0;
  }
  a {
    padding: 10px 0 10px 15px;
    &:hover,
    &:focus,
    &:active {
      text-decoration: none;
    }
  }
  ul a {
    font-size: 13px;
    padding-left: 30px;
  }

  > li {
    > a {
      border-top: 1px solid rgba(0, 0, 0, .1);
      .box-shadow(inset 0 1px 0 rgba(255, 255, 255, .05));
      text-shadow: 0 1px 0 rgba(0, 0, 0, .5);
      padding: 10px 0 10px 15px;
    }
    &.active > a {
      background-color: rgba(0, 0, 0, .1);
      .box-shadow(0px 1px 3px rgba(0, 0, 0, 0.1) inset);
    }
    &:hover > a, &:focus > a {
      background-color:rgba(0, 0, 0, .1);
      outline: none;
      .box-shadow(none);
    }
  }

  > li ul {
    .box-shadow(inset 0 1px 0 rgba(255, 255, 255, .05));
    border-left-width: 0;
    a {
      padding: 11px 0 11px 30px;
      font-size: 13px;

      &:hover {
        background-color: rgba(0, 0, 0, .1);
      }
    }
  }
  .nav-header {
    padding: 3px 15px !important;
    text-transform: uppercase;
    font-weight: bold;
    font-size: 12px;
    border-top: 1px solid rgba(0, 0, 0, 0.1);
    .box-shadow(0px 1px 0px rgba(255, 255, 255, 0.05) inset);
    text-shadow: 0px 1px 0px rgba(0, 0, 0, 0.5);
    background: rgba(0, 0, 0, .1);
  }
  .nav-divider {
    height: 1rem;
    margin: 0;
    background: rgba(0, 0, 0, 0.2);
    .box-shadow(0px 1px 3px rgba(0, 0, 0, 0.1) inset);
  }
}

@media (max-width: 1249px) {
  #menu {
.nav-divider,
.nav-header {
  display: none;
}
      > li > ul {
        position: absolute;
        top: 0;
        left: 100%;
        .box-shadow(none);
        min-width: 200px;
        z-index: 1;
        background-color: rgba(0,0,0,0.8);
        display: none;
        top: 100%;
      }

      > li:hover > ul {
          display: inherit;
          visibility: visible;
      }
      > li > a {
          .fa {font-size: 18px;}
          .fa.arrow {display: none;}
          .link-title {
              border-top: 1px solid rgba(0, 0, 0, 0.1);
              border-right: 1px solid rgba(0, 0, 0, 0.1);
              .box-shadow(inset 0 1px 0 rgba(255, 255, 255, .05));
              position: absolute;
              left: 100%;
              top: 0;
              z-index: 1;
              background: rgba(0, 0, 0, .85);
              display: none;
              padding: 10px 30px;
          }
      }

      > li:hover > a > .link-title {display: block;min-width: 200px;}
  }
}

#menu {
  .fa.arrow {
    float: right;
    padding-top: 3px;
    margin-right: 15px;
  }

  .fa.arrow:before {
    content: "\f104";
  }

  .active > a > .fa.arrow:before {
    content: "\f107";
  }

}
```
Happy if I can help you.
